from __future__ import annotations

import secrets
import string

# Short, inoffensive words only, so a three-word name stays close to the
# 22-character target most of the time without a hard length limit.
ADJECTIVES = [
    "brave",
    "breezy",
    "calm",
    "chilly",
    "clever",
    "cozy",
    "curious",
    "dapper",
    "daring",
    "dusty",
    "eager",
    "earnest",
    "fair",
    "fancy",
    "feisty",
    "fresh",
    "frosty",
    "gentle",
    "glossy",
    "gritty",
    "happy",
    "hardy",
    "hasty",
    "hazy",
    "humble",
    "husky",
    "jaunty",
    "jolly",
    "keen",
    "lively",
    "lofty",
    "lucky",
    "mellow",
    "merry",
    "mighty",
    "misty",
    "nifty",
    "nimble",
    "perky",
    "plain",
    "plucky",
    "proud",
    "quiet",
    "quirky",
    "rosy",
    "rustic",
    "salty",
    "sandy",
    "scrappy",
    "shiny",
    "silent",
    "sleepy",
    "snug",
    "spare",
    "sporty",
    "spry",
    "stormy",
    "sturdy",
    "sunny",
    "swift",
    "thrifty",
    "tidy",
    "vivid",
    "wispy",
    "witty",
    "zany",
    "zesty",
]

DESCRIPTORS = [
    "amber",
    "azure",
    "bronze",
    "cedar",
    "cherry",
    "citrus",
    "clover",
    "cobalt",
    "copper",
    "coral",
    "crimson",
    "denim",
    "ebony",
    "emerald",
    "fern",
    "flint",
    "frost",
    "golden",
    "granite",
    "hazel",
    "indigo",
    "ivory",
    "jade",
    "lilac",
    "linen",
    "marble",
    "maroon",
    "mint",
    "moss",
    "navy",
    "ochre",
    "olive",
    "onyx",
    "opal",
    "pearl",
    "pepper",
    "pine",
    "plum",
    "quartz",
    "ruby",
    "rust",
    "sable",
    "saffron",
    "sage",
    "scarlet",
    "sepia",
    "sienna",
    "silver",
    "slate",
    "spruce",
    "tawny",
    "teal",
    "topaz",
    "tundra",
    "umber",
    "violet",
    "walnut",
    "willow",
]

NOUNS = [
    "aurora",
    "badger",
    "beaver",
    "bison",
    "camel",
    "canyon",
    "comet",
    "condor",
    "cove",
    "crane",
    "delta",
    "dolphin",
    "dune",
    "eagle",
    "egret",
    "elk",
    "falcon",
    "finch",
    "fjord",
    "fox",
    "gecko",
    "glacier",
    "grove",
    "gull",
    "harbor",
    "haven",
    "hawk",
    "heron",
    "ibis",
    "island",
    "jay",
    "kestrel",
    "kite",
    "koala",
    "lagoon",
    "llama",
    "lynx",
    "magpie",
    "meadow",
    "mesa",
    "meteor",
    "moose",
    "nebula",
    "oasis",
    "orchard",
    "osprey",
    "otter",
    "owl",
    "panda",
    "panther",
    "parrot",
    "peak",
    "pelican",
    "penguin",
    "plateau",
    "plover",
    "prairie",
    "puffin",
    "quail",
    "rabbit",
    "raven",
    "reef",
    "ridge",
    "robin",
    "shore",
    "sparrow",
    "stork",
    "summit",
    "swan",
    "tern",
    "thrush",
    "tiger",
    "trail",
    "turtle",
    "valley",
    "vulture",
    "whale",
    "wolf",
    "wren",
    "yak",
]


# len(ADJECTIVES) * len(DESCRIPTORS) * len(NOUNS) is only in the hundreds of
# thousands, which is too small a space to safely avoid collisions across many
# organizations/projects. A random suffix from this alphabet pushes the total
# number of possible names into the tens of billions.
SUFFIX_ALPHABET = string.ascii_lowercase + string.digits
SUFFIX_LENGTH = 4


def generate_fake_name() -> str:
    """Suggest a random name, e.g. "Brave Amber Otter-4f2a".

    Meant as a stand-in for a real organization or project name: someone who
    wants to keep what they work on private can accept the suggestion, or
    edit it, instead of typing in something identifying.
    """
    words = (
        secrets.choice(ADJECTIVES),
        secrets.choice(DESCRIPTORS),
        secrets.choice(NOUNS),
    )
    suffix = "".join(secrets.choice(SUFFIX_ALPHABET) for _ in range(SUFFIX_LENGTH))
    name = " ".join(word.capitalize() for word in words)
    return f"{name}-{suffix}"
