[tox]
requires =
    tox>=4.22
    tox-uv>=1.20
env_list =
    py314-django60
    py313-django{60, 52}
    py312-django{60, 52, 50}
    py311-django{52, 50}
    py310-django{52, 50}

[testenv]
runner = uv-venv-lock-runner
package = wheel
wheel_build_env = .pkg
commands =
    python -m pytest {posargs:tests}
dependency_groups =
    server
    test
    django50: django50
    django52: django52
    django60: django60
