# Generated by Django 6.1 on 2026-09-03 15:19

import django.db.models.deletion
import ingest.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0003_organization_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='CliCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=ingest.models._generate_cli_credential_code, editable=False, help_text='Ephemeral device-flow secret embedded in the verify URL and used for polling.', max_length=64, unique=True)),
                ('token', models.CharField(blank=True, editable=False, help_text='The long-lived CLI credential, issued once the request is approved.', max_length=64, null=True, unique=True)),
                ('label', models.CharField(blank=True, help_text='Optional human-readable name for the device, e.g. a hostname.', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=ingest.models._cli_auth_request_expiry)),
                ('denied_at', models.DateTimeField(blank=True, null=True)),
                ('retrieved_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('requested_org_slug', models.CharField(blank=True, editable=False, max_length=220)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cli_credentials', to='ingest.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cli_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
