# Generated by Django 6.1 on 2026-09-06 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0007_submission_django_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='organization',
        ),
    ]
