# Generated by Django 6.1 on 2026-09-16 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0010_submission_package_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='dependencies_source',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
