# Generated by Django 6.1 on 2026-09-24 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0011_submission_dependencies_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='project',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='ingest.project'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['project', '-created_at'], name='submission_project_latest'),
        ),
    ]
