name: Django Probe

on:
  schedule:
    # Runs monthly. Choose a different minute and hour to help spread load on our servers.
    - cron: "11 12 1 * *"
  workflow_dispatch:

permissions: {}

jobs:
  django-probe:
    uses: ./.github/workflows/django-probe-submit-uv.yml
    secrets:
      DJANGO_PROBE_TOKEN: ${{ secrets.DJANGO_PROBE_TOKEN }}
